name: 'Create Repository Manifest'
description: 'Creates a JSON manifest of all files in the repository along with the most recent commit SHA that modified them.'
author: 'Danielle Church'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'file-text'
  color: 'blue'

# Define your inputs here.
inputs:
  include-files:
    description: 'What files to include in the manifest'
    default: '**'
  exclude-files:
    description: 'What files to exclude from the manifest, even if they'
    required: false
  follow-symlinks:
    description: 'Whether to follow symlinks when creating the manifest'
    default: true
  manifest-path:
    description: 'The path to the manifest JSON to generate'
    default: '/repository-manifest.json'
  summary-path:
    description: 'The path to a summary JSON to generate'
    required: false
  minify:
    description: 'Whether to output the JSON in compact form'
    default: true

# Define your outputs here.
outputs:
  manifest:
    description: 'The manifest JSON'
  summary:
    description: 'The summary JSON'

runs:
  using: node20
  main: dist/index.js
